#!/bin/bash

# This will run the samples, build some source files, and then compile and install the html documentation.
# To run the samples the option -run-samples must be given

if [ "$1" == "-run-samples" ]
then
    cd samples
    ./run-samples
    cd -   > /dev/null
fi

./install-quickstart

make html
cp -rf _build/html/* ../html
