#!/bin/bash

# This script is a utility for building the documentation, not intended for end users.

for d in *
do
    if test -d "$d" 
    then
        echo running "$d"
        cd "$d"
        ./run
        cd -   > /dev/null
    fi
done

